# ============================
# Stage 1 — Build Shopizz
# ============================

# Use Node.js 20 with Alpine Linux as our base environment.
# "AS builder" gives this build stage a name that we can reference later.
FROM node:24-alpine AS builder

# Set the working directory inside the container.
# All following commands in this stage will run from /app.
WORKDIR /app

# Copy the dependency definition and lockfile into the container.
# Docker will use these files to install the exact dependency tree.
COPY package.json package-lock.json ./

# Install dependencies exactly as defined in package-lock.json.
# This creates node_modules inside the builder container.
RUN npm ci

# Copy the remaining Shopizz source code into the builder container.
# Files excluded by .dockerignore will not be copied.
COPY . .

# Build the Nuxt application for production.
# Nuxt will generate the production-ready .output directory.
RUN npm run build


# ============================
# Stage 2 — Run Shopizz
# ============================

# Use Node.js 24 with Alpine Linux for the production container.
# This stage contains only what is needed to run the built application.
FROM node:24-alpine AS production

# Set the working directory inside the production container.
# Shopizz will run from this directory.
WORKDIR /app

# Copy the production build generated by Nuxt from the builder stage.
# Only the built application is copied into the production image.
COPY --from=builder /app/.output ./.output

# Document the port that the Nuxt production server listens on.
# EXPOSE does not publish the port to the host machine.
EXPOSE 3000

# Start the Nuxt production server when the container starts.
# Nuxt's production server entry point is generated inside .output.
CMD ["node", ".output/server/index.mjs"]